language: python
python:
  - "3.6"
cache: pip
branches:
  only:
  - /.*/
install:
  - pip install --upgrade pip
  - pip install -r requirements_test.txt
  - python setup.py install
script:
  - black --check flagset/ tests/ setup.py
  - flake8 --count --config=setup.cfg
  - py.test -v --cov=flagset/ tests/ --cov coveralls --cov-report term-missing --doctest-modules
after_success:
  - coveralls
